# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Music' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Music
  pod 'MJRefresh', '3.1.15'
  pod 'MJExtension', '3.0.13'
end
