# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Music' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Music
  pod 'AFNetworking', '3.1.0’
  pod 'MJRefresh', '3.1.15'
  pod 'MJExtension', '3.0.13'
  pod 'DOUAudioStreamer', '0.2.15'
  pod 'SnapKit', '3.2.0'
  pod 'SDWebImage', '4.2.2'
  pod 'RealmSwift', '3.0.2'
end
